import { describe, expect, it } from "vitest"
import source from "./PptSolutionWorkspaceView.vue?raw"

describe("PptSolutionWorkspaceView", () => {
  it("uses Type-5-only plans with on-demand product details", () => {
    expect(source).toContain("本次推品方案")
    expect(source).toContain("配置数量作为方案目标")
    expect(source).toContain("实际 {{ plan.candidate_ids.length }} / 目标")
    expect(source).toContain("planAvailability")
    expect(source).toContain("每档真实数量")
    expect(source).toContain("具体商品详情")
    expect(source).toContain("确认本方案商品")
    expect(source).toContain("plan-card--selected")
    expect(source).toContain("已选方案")
    expect(source).toContain("已选择此方案")
    expect(source).toContain("pptSolutionApi.selectPlan(plan.id)")
    expect(source).toContain("重新生成推品")
    expect(source).toContain("本次推品执行失败，请修改配置后重新生成。")
    expect(source).not.toContain("AI 推荐与人工选品")
    expect(source).not.toContain("全选待确认商品")
    expect(source).not.toContain("方案总价：")
    expect(source).toContain("组成套装")
    expect(source).toContain("组套仅用于把多件商品合成一页")
    expect(source).toContain("完成选品")
    expect(source).toContain("formatMoney")
    expect(source).toContain("固定使用系统默认模板")
    expect(source).toContain("生成系统 PPT")
    expect(source).toContain("下载 PPTX")
  })
})
