import { describe, expect, it } from "vitest"
import source from "./PptSolutionWorkspaceView.vue?raw"

describe("PptSolutionWorkspaceView", () => {
  it("uses one AI-matched candidate table with per-band quantities", () => {
    expect(source).toContain("价格档 / AI 匹配商品数量")
    expect(source).toContain("item_count")
    expect(source).toContain("AI 匹配商品与人工确认")
    expect(source).toContain("全选所有待确认")
    expect(source).toContain("selectAllUnconfirmedCandidates")
    expect(source).toContain("excludedCandidateIds")
    expect(source).toContain("jumper")
    expect(source).toContain("批量确认选中")
    expect(source).toContain("每档只匹配该档指定数量的商品")
    expect(source).not.toContain("确认本方案商品")
    expect(source).not.toContain("plan-card--selected")
    expect(source).not.toContain("pptSolutionApi.selectPlan")
    expect(source).not.toContain("重试未完成方案")
    expect(source).not.toContain(">混合推品<")
    expect(source).toContain("重新生成推品")
    expect(source).toContain("组成套装")
    expect(source).toContain("完成选品")
    expect(source).toContain("formatMoney")
    expect(source).toContain("template-gallery")
    expect(source).toContain("selectedTemplateCode")
    expect(source).toContain("pptSolutionApi.templates")
    expect(source).toContain("selectedTemplateCode.value")
    expect(source).toContain("生成 PPT")
    expect(source).toContain("下载 PPTX")
  })
})
