import { describe, expect, it } from "vitest"
import source from "./PptSolutionWorkspaceView.vue?raw"

describe("PptSolutionWorkspaceView", () => {
  it("keeps direct candidate matching while rendering combination groups separately", () => {
    expect(source).toContain("价格档 / AI 匹配商品数量")
    expect(source).toContain("item_count")
    expect(source).toContain("AI 匹配商品与人工确认")
    expect(source).toContain("本次冻结候选池")
    expect(source).toContain("冻结候选")
    expect(source).toContain("AI 正在后台匹配商品")
    expect(source).toContain("startRunPolling")
    expect(source).toContain("QUEUED")
    expect(source).toContain("全选所有待确认")
    expect(source).toContain("selectAllUnconfirmedCandidates")
    expect(source).toContain("excludedCandidateIds")
    expect(source).toContain("jumper")
    expect(source).toContain("批量确认选中")
    expect(source).toContain("每档只匹配该档指定数量的商品")
    expect(source).not.toContain("确认本方案商品")
    expect(source).not.toContain("plan-card--selected")
    expect(source).toContain("组合总价 / AI 生成组合数量")
    expect(source).toContain("每组固定 2～4 件")
    expect(source).toContain("AI 组合推品与人工确认")
    expect(source).toContain("pptSolutionApi.selectPlan")
    expect(source).toContain("confirmCombination")
    expect(source).not.toContain("重试未完成方案")
    expect(source).not.toContain(">混合推品<")
    expect(source).toContain("重新生成推品")
    expect(source).toContain("组成套装")
    expect(source).toContain("完成选品")
    expect(source).toContain("formatMoney")
    expect(source).toContain("template-gallery")
    expect(source).toContain("selectedTemplateCode")
    expect(source).toContain("pptSolutionApi.templates")
    expect(source).toContain("selectedTemplateCode.value")
    expect(source).toContain("生成 PPT")
    expect(source).toContain("下载 PPTX")
  })

  it("validates every price band before posting the configuration", () => {
    expect(source).toContain("validatePriceBands")
    expect(source).toContain("最高价必填")
    expect(source).toContain("最低价不能大于最高价")
    expect(source).toContain("价格区间与第")
    expect(source).toContain("countLabel")
    expect(source).toContain("maxCount")
    expect(source).toContain("priceBandErrors[index]")
    expect(source).toContain("if (!validatePriceBands())")
  })
})
